name: rsue_schedule_api
description: Package for working with the schedule API of the RSUE 
version: 0.0.4

environment:
  sdk: '>=2.17.0-148.0.dev <3.0.0'

dependencies:
  html: ^0.15.0
  dio: ^4.0.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
