name: rsue_schedule_api
description: Package for working with the schedule API of the RSUE 
version: 0.1.1

environment:
  sdk: '>=2.17.0-148.0.dev <3.0.0'

dependencies:
  json_annotation: ^4.4.0
  week_of_year: ^2.0.0
  html: ^0.15.0
  dio: ^4.0.4

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^1.0.0
  test: ^1.16.0
